BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE1';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE1(COL1 NUMBER);
INSERT INTO SAMPLE1 VALUES(1);
SAVEPOINT SP1;
INSERT INTO SAMPLE1 VALUES(2);
SAVEPOINT SP2;
ROLLBACK TO SP1;
INSERT INTO SAMPLE1 VALUES(3);
COMMIT;

SELECT * FROM SAMPLE1;
