BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE1';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE2';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE1(
	COL1	NUMBER,
	COL2    VARCHAR(10)
);

CREATE TABLE SAMPLE2(
	COL1	NUMBER,
	COL2    VARCHAR(10)
);

INSERT INTO SAMPLE1 VALUES(10, 'APPLE');
INSERT INTO SAMPLE1 VALUES(20, 'ORANGE');

INSERT INTO SAMPLE2 VALUES(10, 'PINEAPPLE');
INSERT INTO SAMPLE2 VALUES(20, 'ORANGE');
INSERT INTO SAMPLE2 VALUES(30, 'GRAPE');
INSERT INTO SAMPLE2 VALUES(40, 'BANANA');
INSERT INTO SAMPLE2 VALUES(50, 'MELON');

COMMIT;


MERGE INTO SAMPLE1 A
USING SAMPLE2 B
   ON (A.COL1 = B.COL1)
 WHEN MATCHED THEN
      UPDATE SET A.COL2 = B.COL2
 WHEN NOT MATCHED THEN
      INSERT(A.COL1, A.COL2) VALUES(B.COL1, B.COL2);

SELECT * FROM SAMPLE1;
