BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE(
    COL1 NUMBER PRIMARY KEY,
    COL2 VARCHAR(1)
);

INSERT INTO SAMPLE VALUES(1, 'A');
INSERT INTO SAMPLE VALUES('1', 'A');
INSERT INTO SAMPLE VALUES('A', 1);
INSERT INTO SAMPLE VALUES(1, 2);
