BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE1';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE2';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE1 (COL1 NUMBER, COL2 NUMBER);
INSERT INTO SAMPLE1 VALUES (10, 10);
INSERT INTO SAMPLE1 VALUES (20, 20);
CREATE TABLE SAMPLE2 (COL1 NUMBER, COL2 NUMBER); 
INSERT INTO SAMPLE2 VALUES (10, 30);
ROLLBACK;
INSERT INTO SAMPLE2 VALUES (20, 40); 
COMMIT;


SELECT COUNT(*)
  FROM SAMPLE1 A, SAMPLE2 B
 WHERE A.COL1 = B.COL1; 