-- SELECT STUDENT_NO, AVG(MATH_SCORE) AS AVG
-- FROM STUDENT_SCORE
-- WHERE YEAR = '2021' AND SEMESTER = '1' AND AVG >= 90;

-- SELECT STUDENT_NO, AVG(MATH_SCORE) AS AVG
-- FROM STUDENT_SCORE
-- GROUP BY STUDENT_NO
-- WHERE YEAR = '2021' AND SEMESTER = '1' AND AVG >= 90;

SELECT STUDENT_NO, AVG(MATH_SCORE) AS AVG
FROM STUDENT_SCORE
WHERE YEAR = '2021' AND SEMESTER = '1'
GROUP BY STUDENT_NO
HAVING AVG(MATH_SCORE) >= 90;

-- SELECT STUDENT_NO, AVG(MATH_SCORE) AS AVG
-- FROM STUDENT_SCORE
-- WHERE YEAR = '2021' AND SEMESTER = '1'
-- GROUP BY STUDENT_NO
-- HAVING AVG >= 90;
