SELECT STUDENT_NO AS S_NO, SCORE AS SCR
FROM STUDENT_SCORE
ORDER BY SCORE;

SELECT STUDENT_NO AS S_NO, SCORE AS SCR
FROM STUDENT_SCORE
ORDER BY SCR DESC;

SELECT STUDENT_NO AS S_NO, SCORE AS SCR
FROM STUDENT_SCORE
ORDER BY SCORE DESC;

-- SELECT STUDENT_NO AS S_NO, SCORE AS SCR
-- FROM STUDENT_SCORE
-- ORDER BY S_NO, SCR ASC DESC;
