BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE1';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE2';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE1 (
	COL1	NUMBER,
	COL2	NUMBER
);

CREATE TABLE SAMPLE2 (
	COL1	NUMBER,
	COL2	NUMBER,
	COL3	NUMBER
);

INSERT INTO SAMPLE1 VALUES(11,21);
INSERT INTO SAMPLE1 VALUES(21,31);
INSERT INTO SAMPLE1 VALUES(31,41);
INSERT INTO SAMPLE1 VALUES(41,51);
INSERT INTO SAMPLE1 VALUES(51,61);

INSERT INTO SAMPLE2 VALUES(15,25,35);
INSERT INTO SAMPLE2 VALUES(25,35,45);
INSERT INTO SAMPLE2 VALUES(35,45,55);
INSERT INTO SAMPLE2 VALUES(45,55,65);
INSERT INTO SAMPLE2 VALUES(55,65,75);

COMMIT;


SELECT A.COL1, B.COL3
  FROM SAMPLE1 A, SAMPLE2 B
 WHERE A.COL1 >= B.COL1 
   AND A.COL1 <= B.COL2;

SELECT A.COL1, B.COL3
  FROM SAMPLE1 A, SAMPLE2 B
 WHERE A.COL1 BETWEEN B.COL1 AND B.COL2;
 
SELECT A.COL1, B.COL3
  FROM SAMPLE1 A, SAMPLE2 B 
 WHERE B.COL1 <= A.COL1
   AND B.COL2 >= A.COL1;
   
SELECT B.COL1, B.COL3
  FROM SAMPLE1 A, SAMPLE2 B 
 WHERE A.COL1 >= B.COL1
   AND A.COL1 <= B.COL2;
