CREATE TABLE SAMPLE1 (
	COL1	VARCHAR2(3),
	COL2	INT,
	COL3	VARCHAR2(1)
);

CREATE TABLE SAMPLE2 (
	COL1	VARCHAR2(3),
	COL4	INT
);


INSERT INTO SAMPLE1 VALUES ('가',10,'A');
INSERT INTO SAMPLE1 VALUES ('나',11,'A');
INSERT INTO SAMPLE1 VALUES ('다',20,'C');
INSERT INTO SAMPLE1 VALUES ('라',15,'B');
INSERT INTO SAMPLE1 VALUES ('마',5,'C');

INSERT INTO SAMPLE2 VALUES ('가',100);
INSERT INTO SAMPLE2 VALUES ('나',0);
INSERT INTO SAMPLE2 VALUES ('다',50);