BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE1';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE2';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE1 (
	COL1	VARCHAR2(3),
	COL2	INT,
	COL3	VARCHAR2(1)
);

CREATE TABLE SAMPLE2 (
	COL1	VARCHAR2(3),
	COL4	INT
);


INSERT INTO SAMPLE1 VALUES ('가',10,'A');
INSERT INTO SAMPLE1 VALUES ('나',11,'A');
INSERT INTO SAMPLE1 VALUES ('다',20,'C');
INSERT INTO SAMPLE1 VALUES ('라',15,'B');
INSERT INTO SAMPLE1 VALUES ('마',5,'C');

INSERT INTO SAMPLE2 VALUES ('가',100);
INSERT INTO SAMPLE2 VALUES ('나',0);
INSERT INTO SAMPLE2 VALUES ('다',50);

COMMIT;

-- ORA-00918: 열의 정의가 애매합니다
-- SELECT COL1, COL3
--   FROM SAMPLE A, SAMPLE2 B
--  WHERE A.COL1 = B.COL1;

SELECT COL3, B.COL4
  FROM SAMPLE1 A, SAMPLE2 B
 WHERE A.COL1 = B.COL1;

SELECT A.COL2, COL3
  FROM SAMPLE1 A, SAMPLE2 B
 WHERE A.COL1 = B.COL1;

SELECT B.COL1, B.COL4
  FROM SAMPLE1 A, SAMPLE2 B
 WHERE A.COL1 = B.COL1;
