BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE1';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE2';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE1 (
    COL1    VARCHAR(4),
	COL2	NUMBER,
	COL3	VARCHAR(4)
);

CREATE TABLE SAMPLE2 (
	COL1	VARCHAR(4),
	COL2	NUMBER
);

INSERT INTO SAMPLE1 VALUES('가',100,'A');
INSERT INTO SAMPLE1 VALUES('나',110,'A');
INSERT INTO SAMPLE1 VALUES('다',200,NULL);
INSERT INTO SAMPLE1 VALUES('라',150,'B');
INSERT INTO SAMPLE1 VALUES('마',50,NULL);

INSERT INTO SAMPLE2 VALUES('가',10);
INSERT INTO SAMPLE2 VALUES('나',0);
INSERT INTO SAMPLE2 VALUES('다',5);

COMMIT;


SELECT SUM(A.COL2) AS RESULT1,
       COUNT(A.COL3) AS RESULT2,
       COUNT(DISTINCT A.COL3) AS RESULT3
  FROM SAMPLE1 A, SAMPLE2 B
 WHERE A.COL1 = B.COL1;
