BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE1';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE2';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE1 (
    COL1    NUMBER,
	COL2	VARCHAR(4)
);

CREATE TABLE SAMPLE2 (
	COL1	NUMBER,
	COL2	VARCHAR(4)
);

INSERT INTO SAMPLE1 VALUES(2,'G');
INSERT INTO SAMPLE1 VALUES(3,'H');
INSERT INTO SAMPLE1 VALUES(3,'I');

INSERT INTO SAMPLE2 VALUES(1,'A');
INSERT INTO SAMPLE2 VALUES(2,'B');
INSERT INTO SAMPLE2 VALUES(3,NULL);
INSERT INTO SAMPLE2 VALUES(4,'D');
INSERT INTO SAMPLE2 VALUES(5,'E');

COMMIT;
