BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE1';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE2';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE1 (
    COL1    NUMBER,
	COL2	VARCHAR(4),
	COL3	VARCHAR(4)
);

CREATE TABLE SAMPLE2 (
	COL1	NUMBER,
	COL4	VARCHAR(4)
);

INSERT INTO SAMPLE1 VALUES(1,'A','D');
INSERT INTO SAMPLE1 VALUES(3,'B','E');
INSERT INTO SAMPLE1 VALUES(5,'C','F');

INSERT INTO SAMPLE2 VALUES(2,'G');
INSERT INTO SAMPLE2 VALUES(3,'H');
INSERT INTO SAMPLE2 VALUES(3,'I');

COMMIT;


SELECT *
  FROM SAMPLE1 A LEFT OUTER JOIN SAMPLE2 B
    ON A.COL1 = B.COL1;

SELECT *
  FROM SAMPLE1 A RIGHT OUTER JOIN SAMPLE2 B
    ON A.COL1 = B.COL1;

SELECT *
  FROM SAMPLE1 A FULL OUTER JOIN SAMPLE2 B
    ON A.COL1 = B.COL1;
