BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE1';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE2';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE1 (
    COL1    VARCHAR(4),
	COL2	NUMBER,
	COL3    VARCHAR(4)
);

CREATE TABLE SAMPLE2 (
	COL1	VARCHAR(4),
	COL2	NUMBER
);

INSERT INTO SAMPLE1 VALUES('A', 10, '가');
INSERT INTO SAMPLE1 VALUES('B', 15, NULL);
INSERT INTO SAMPLE1 VALUES('C', 20, '다');

INSERT INTO SAMPLE2 VALUES('A', NULL);
INSERT INTO SAMPLE2 VALUES('A', 10);
INSERT INTO SAMPLE2 VALUES('B', 15);

COMMIT;


CREATE VIEW V_SAMPLE1 AS
    SELECT COL1, COL2
      FROM SAMPLE1
     WHERE COL3 IS NOT NULL;

SELECT COUNT(*)
  FROM V_SAMPLE1 NATURAL JOIN SAMPLE2;
