BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE (
    COL1    VARCHAR(4) PRIMARY KEY,
	COL2	VARCHAR(4),
	COL3    VARCHAR(4) DEFAULT 'D'
);

INSERT INTO SAMPLE(COL2, COL3) VALUES('S', 'A');
