BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE (
    COL1    NUMBER,
	COL2	NUMBER,
	COL3    VARCHAR(4)
);

INSERT INTO SAMPLE(COL1, COL2, COL3) VALUES(0, 2, 'B');
INSERT INTO SAMPLE(COL1, COL2, COL3) VALUES(1, 3, 'A');
INSERT INTO SAMPLE(COL1, COL2, COL3) VALUES(2, 4, 'B');

SELECT * FROM SAMPLE;

UPDATE SAMPLE SET COL2 = COL1 + COL2 WHERE COL3 = 'B';

SELECT * FROM SAMPLE;
