BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE1';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE2';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE1 (
    COL1    NUMBER,
	COL2	VARCHAR(4),
	COL3    VARCHAR(4)
);

CREATE TABLE SAMPLE2 (
    COL1    VARCHAR(4),
	COL2	NUMBER
);

INSERT INTO SAMPLE1 VALUES(1, '가', 'A');
INSERT INTO SAMPLE1 VALUES(2, '나', 'B');
INSERT INTO SAMPLE1 VALUES(3, '다', 'C');

INSERT INTO SAMPLE2 VALUES('B', 10);
INSERT INTO SAMPLE2 VALUES('A', 12);
INSERT INTO SAMPLE2 VALUES('B', 11);

DELETE FROM SAMPLE1 A
 WHERE NOT EXISTS(SELECT 1 FROM SAMPLE2 B
                   WHERE A.COL3 = B.COL1);

SELECT * FROM SAMPLE1;
