BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE (
    COL1    NUMBER,
	COL2	VARCHAR(4),
	COL3    VARCHAR(4)
);

INSERT INTO SAMPLE VALUES(1, '가', 'A');
INSERT INTO SAMPLE VALUES(2, '나', 'B');
INSERT INTO SAMPLE VALUES(3, '다', 'C');


INSERT INTO SAMPLE VALUES (4, '라', 'D');
SAVEPOINT A;
UPDATE SAMPLE SET COL2 = '나' WHERE COL1 IN (1, 3);
SAVEPOINT B;
DELETE FROM SAMPLE WHERE COL2 = '라';
ROLLBACK TO A;
DELETE FROM SAMPLE WHERE COL2 = '나';
COMMIT;

SELECT * FROM SAMPLE;
