BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE(
    COL1 INT,
    COL2 INT
);
INSERT INTO SAMPLE VALUES (10, 5);
INSERT INTO SAMPLE VALUES (20, NULL);
INSERT INTO SAMPLE VALUES (NULL, NULL);

SELECT COL1 + COL2 AS RESULT FROM SAMPLE;
