BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SAMPLE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

CREATE TABLE SAMPLE(
    COL1 VARCHAR(32),
    COL2 VARCHAR(32)
);
INSERT INTO SAMPLE VALUES ('ORACLE', 'DATABASE');
INSERT INTO SAMPLE VALUES ('SQL', 'DEVELOPER');

SELECT LENGTH(SUBSTR(COL1,3,3)) + LENGTH(SUBSTR(COL2,2)) AS RESULT
FROM SAMPLE;
