BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SAMPLE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

CREATE TABLE SAMPLE(
    COL1 VARCHAR(32),
    COL2 VARCHAR(32)
);
INSERT INTO SAMPLE VALUES ('ORACLE', 'DATABASE');
INSERT INTO SAMPLE VALUES ('SQL', 'DEVELOPER');

SELECT LENGTH(RTRIM(COL1,'LE')) + LENGTH(LTRIM(COL2,'DE')) AS RESULT
FROM SAMPLE;
