DROP TABLE IF EXISTS SAMPLE;
CREATE TABLE SAMPLE(
    COL1 VARCHAR(32)
);
INSERT INTO SAMPLE VALUES ('ORACLE');
INSERT INTO SAMPLE VALUES ('SQL');

SELECT REPLACE((REPLACE(COL1, 'L', 'A')), 'A') AS RESULT
FROM SAMPLE;
