BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE(
    COL1 VARCHAR(32)
);
INSERT INTO SAMPLE VALUES ('ORACLE');
INSERT INTO SAMPLE VALUES ('SQL');

SELECT REPLACE((REPLACE(COL1, 'L', 'A')), 'A') AS RESULT
FROM SAMPLE;
