BEGIN
EXECUTE IMMEDIATE 'DROP TABLE ENTERTAINER';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE ENTERTAINER (
    NAME VARCHAR(16),
    JOB VARCHAR(32),
    BIRTHDAY VARCHAR(16),
    AGENCY_NAME VARCHAR(32)
);
INSERT INTO ENTERTAINER VALUES ('이지은', '가수,배우,작곡가', '19930516', 'EDAM엔터테인먼트');
INSERT INTO ENTERTAINER VALUES ('김향기', '배우', '20000809', '지킴엔터테인먼트');
INSERT INTO ENTERTAINER VALUES ('김태형', '가수,작곡가', '19951230', NULL);
INSERT INTO ENTERTAINER VALUES ('유건우', '배우', '19830925', '지킴엔터테인먼트');

SELECT *
FROM ENTERTAINER
WHERE NAME = '이지은';

SELECT *
FROM ENTERTAINER
WHERE NAME <> '이지은';

UPDATE ENTERTAINER SET AGENCY_NAME = '빅히트뮤직' WHERE NAME = '김태형';

DELETE FROM ENTERTAINER WHERE JOB = '배우';
