SELECT FIRST_NAME, LAST_NAME, CITY
FROM MEMBER
WHERE CITY = 'Paris';

SELECT MEMBER_NO, FIRST_NAME, LAST_NAME
FROM MEMBER
WHERE MEMBER_NO < 10;

-- ORA-01722: 수치가 부적합합니다
-- SELECT FIRST_NAME, LAST_NAME, EMAIL
-- FROM MEMBER
-- WHERE FIRST_NAME = Mark;
