SELECT PLAY_ID, NAME, FAVORITES
FROM PLAY_LIST
WHERE NAME LIKE '%Music';

SELECT PLAY_ID, NAME, FAVORITES
FROM PLAY_LIST
WHERE NAME LIKE 'M%s';

SELECT PLAY_ID, NAME, FAVORITES
FROM PLAY_LIST
WHERE NAME LIKE '%101%';

SELECT LAST_NAME, FIRST_NAME, TITLE
FROM EMPLOYEE
WHERE TITLE IN ('IT Staff', 'IT Manager');

SELECT LAST_NAME, FIRST_NAME, TITLE
FROM EMPLOYEE
WHERE (TITLE = 'IT Staff' OR TITLE = 'IT Manager');
