SELECT PLAY_ID, NAME, FAVORITES
FROM PLAY_LIST
WHERE NOT (PLAY_ID BETWEEN 1 AND 5);

SELECT PLAY_ID, NAME, FAVORITES
FROM PLAY_LIST
WHERE NOT (PLAY_ID >= 1 AND PLAY_ID <= 5);

SELECT PLAY_ID, NAME, FAVORITES
FROM PLAY_LIST
WHERE PLAY_ID < 1 OR PLAY_ID > 5;

SELECT LAST_NAME, FIRST_NAME, TITLE
FROM EMPLOYEE
WHERE TITLE NOT IN ('IT Staff', 'IT Manager');

SELECT LAST_NAME, FIRST_NAME, TITLE
FROM EMPLOYEE
WHERE NOT (TITLE IN ('IT Staff', 'IT Manager'));

SELECT LAST_NAME, FIRST_NAME, TITLE
FROM EMPLOYEE
WHERE NOT (TITLE = 'IT Staff' OR TITLE = 'IT Manager');

SELECT LAST_NAME, FIRST_NAME, TITLE
FROM EMPLOYEE
WHERE (TITLE <> 'IT Staff' AND TITLE <> 'IT Manager');
