SELECT LAST_NAME, FIRST_NAME, TITLE, CITY
FROM EMPLOYEE
WHERE TITLE = 'Sales Support Agent' AND CITY = 'Calgary';

SELECT LAST_NAME, FIRST_NAME, TITLE, CITY
FROM EMPLOYEE
WHERE TITLE = 'Sales Support Agent' OR CITY = 'Calgary';

SELECT LAST_NAME, FIRST_NAME, TITLE, CITY
FROM EMPLOYEE
WHERE NOT (TITLE = 'Sales Support Agent' OR CITY = 'Calgary');

SELECT LAST_NAME, FIRST_NAME, TITLE, CITY
FROM EMPLOYEE
WHERE TITLE <> 'Sales Support Agent' AND CITY <> 'Calgary';
