BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MEMBERINFO';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

CREATE TABLE MEMBERINFO(
    MEMBER_NO INT,
    NAME VARCHAR(16),
    GRADE VARCHAR(16)
);
INSERT INTO MEMBERINFO VALUES (1, '김가나', '2등급');
INSERT INTO MEMBERINFO VALUES (2, '박다라', '1등급');
INSERT INTO MEMBERINFO VALUES (3, '이마바', '3등급');
INSERT INTO MEMBERINFO VALUES (4, '한사아', '1등급');
INSERT INTO MEMBERINFO VALUES (5, '정자차', '4등급');
INSERT INTO MEMBERINFO VALUES (6, '강카타', '2등급');
INSERT INTO MEMBERINFO VALUES (7, '안파하', '5등급');

SELECT NAME, MEMBER_NO
FROM MEMBERINFO
ORDER BY NAME;

SELECT NAME, MEMBER_NO
FROM MEMBERINFO
ORDER BY NAME DESC;

SELECT GRADE, NAME, MEMBER_NO
FROM MEMBERINFO
ORDER BY GRADE, NAME;

SELECT GRADE, NAME, MEMBER_NO
FROM MEMBERINFO
ORDER BY GRADE DESC, NAME;

SELECT GRADE, NAME, MEMBER_NO
FROM MEMBERINFO
ORDER BY GRADE DESC, NAME DESC;
