-- Non EQUI JOIN
SELECT * FROM PRODUCT_REVIEW;

SELECT * FROM EVENT;

SELECT A.EVENT_NAME, B.MEMBER_ID, B.CONTENT, B.REGDATE
FROM EVENT A, PRODUCT_REVIEW B
WHERE B.REGDATE BETWEEN A.START_DATE AND A.END_DATE;
