-- 3개 이상 TABLE JOIN
SELECT A.PRODUCT_NAME, B.MEMBER_ID, B.CONTENT, C.EVENT_NAME
FROM PRODUCT A, PRODUCT_REVIEW B, EVENT C
WHERE A.PRODUCT_CODE = B.PRODUCT_CODE AND B.REGDATE BETWEEN C.START_DATE AND C.END_DATE;
