-- OUTER JOIN
SELECT * FROM PRODUCT;

SELECT * FROM PRODUCT_REVIEW;

SELECT A.PRODUCT_CODE, A.PRODUCT_NAME, B.MEMBER_ID, B.CONTENT, B.REGDATE
FROM PRODUCT A, PRODUCT_REVIEW B
WHERE A.PRODUCT_CODE = B.PRODUCT_CODE(+);
