SELECT * FROM PRODUCT_REVIEW;

SELECT * FROM PRODUCT;

SELECT A.MEMBER_ID,
       A.CONTENT,
       A.REGDATE,
       B.PRODUCT_CODE,
       B.PRODUCT_NAME
  FROM PRODUCT_REVIEW A RIGHT OUTER JOIN PRODUCT B
    ON A.PRODUCT_CODE = B.PRODUCT_CODE;
