UPDATE INFINITE_CHALLENGE
   SET JOB = 'MC'
 WHERE CAST = '유재석';

SELECT * FROM INFINITE_CHALLENGE;

SELECT *
  FROM RUNNING_MAN A NATURAL JOIN INFINITE_CHALLENGE B;

SELECT CAST,
       GENDER,
       A.JOB AS R_JOB,
       B.JOB AS I_JOB
  FROM RUNNING_MAN A JOIN INFINITE_CHALLENGE B
 USING (CAST, GENDER);
