SELECT * FROM AGENCY;

SELECT * FROM ENTERTAINER;

SELECT NAME, JOB, BIRTHDAY, AGENCY_CODE
  FROM ENTERTAINER
 WHERE AGENCY_CODE = (SELECT AGENCY_CODE
                        FROM AGENCY
                       WHERE AGENCY_NAME='EDAM엔터테인먼트');
