CREATE OR REPLACE VIEW DEPT_MEMBER AS
       SELECT A.DEPARTMENT_ID,
              A.DEPARTMENT_NAME,
              B.FIRST_NAME,
              B.LAST_NAME
         FROM DEPARTMENTS A
         LEFT OUTER JOIN EMPLOYEES B
           ON A.DEPARTMENT_ID = B.DEPARTMENT_ID;

SELECT * FROM DEPT_MEMBER WHERE DEPARTMENT_NAME = 'IT';

SELECT DEPARTMENT_NAME, COUNT(*)
  FROM DEPT_MEMBER
GROUP BY DEPARTMENT_NAME
ORDER BY COUNT(*) DESC;
