SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       SUM(SCORE) OVER(PARTITION BY STUDENT_NAME
                           ORDER BY SUBJECT DESC
                           RANGE UNBOUNDED PRECEDING) AS TOTAL_SCORE
  FROM SQLD;

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       SUM(SCORE) OVER(ORDER BY SCORE DESC) AS TOTAL_SCORE
  FROM SQLD
 WHERE SUBJECT = 'SQL 기본 및 활용';
