SELECT * FROM SQLD;

SELECT MAX(SCORE) AS MAX_SCORE FROM SQLD;

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       MAX(SCORE) OVER(PARTITION BY SUBJECT) AS MAX_SCORE
  FROM SQLD;

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE
  FROM (
      SELECT STUDENT_NAME,
           SUBJECT,
           SCORE,
           MAX(SCORE) OVER(PARTITION BY SUBJECT) AS MAX_SCORE
      FROM SQLD)
 WHERE SCORE = MAX_SCORE;
