SELECT * FROM SQLD;

SELECT MIN(SCORE) AS MIN_SCORE FROM SQLD;

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       MIN(SCORE) OVER(PARTITION BY SUBJECT) AS MIN_SCORE
  FROM SQLD;

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE
  FROM (
      SELECT STUDENT_NAME,
           SUBJECT,
           SCORE,
           MIN(SCORE) OVER(PARTITION BY SUBJECT) AS MIN_SCORE
      FROM SQLD)
 WHERE SCORE = MIN_SCORE;
