-- SQLD 테이블
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SQLD';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SQLD(
    STUDENT_NAME VARCHAR(8),
    SUBJECT VARCHAR(64),
    SCORE NUMBER,
    RESULT VARCHAR(16)
);

INSERT INTO SQLD VALUES ('김기탁', '데이터모델링의 이해', 19, 'PASS');
INSERT INTO SQLD VALUES ('김기탁', 'SQL 기본 및 활용', 77, 'PASS');
INSERT INTO SQLD VALUES ('이솔', '데이터모델링의 이해', 15, 'PASS');
INSERT INTO SQLD VALUES ('이솔', 'SQL 기본 및 활용', 50, 'PASS');
INSERT INTO SQLD VALUES ('김재덕', '데이터모델링의 이해', 7, 'FAIL');
INSERT INTO SQLD VALUES ('김재덕', 'SQL 기본 및 활용', 42, 'PASS');
INSERT INTO SQLD VALUES ('박형준', '데이터모델링의 이해', 16, 'PASS');
INSERT INTO SQLD VALUES ('박형준', 'SQL 기본 및 활용', 62, 'PASS');
INSERT INTO SQLD VALUES ('노정인', '데이터모델링의 이해', 12, 'PASS');
INSERT INTO SQLD VALUES ('노정인', 'SQL 기본 및 활용', 42, 'PASS');

COMMIT;
