SELECT STUDENT_NAME,
       SUBJECT,
       SCORE
  FROM(
      SELECT STUDENT_NAME,
           SUBJECT,
           SCORE,
           ROUND(AVG(SCORE) OVER(PARTITION BY SUBJECT)) AS AVG_SCORE
      FROM SQLD)
 WHERE SCORE >= AVG_SCORE;
