SELECT * FROM SQLD;

SELECT COUNT(*) AS SCORE_COUNT FROM SQLD;

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       COUNT(*) OVER(PARTITION BY SUBJECT) AS PASS_COUNT
  FROM SQLD
 WHERE RESULT = 'PASS';

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       COUNT(*) OVER(PARTITION BY SUBJECT
                         ORDER BY SCORE DESC
                         RANGE UNBOUNDED PRECEDING) AS HIGHER_COUNT
  FROM SQLD;
