SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       COUNT(*) OVER(PARTITION BY SUBJECT
                         ORDER BY SCORE DESC
                         RANGE BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS HIGHER_COUNT
  FROM SQLD;
