SELECT * FROM SQLD;

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       LAG(SCORE, 3) OVER(ORDER BY SCORE) AS LAG
  FROM SQLD;

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       LAG(SCORE) OVER(ORDER BY SCORE) AS LAG
  FROM SQLD;

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       LAG(SCORE, 2) OVER(PARTITION BY SUBJECT
                               ORDER BY SCORE DESC) AS LAG
  FROM SQLD;
