SELECT * FROM SQLD;

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       LEAD(SCORE, 3) OVER(ORDER BY SCORE) AS LEAD
  FROM SQLD;

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       LEAD(SCORE) OVER(ORDER BY SCORE) AS LEAD
  FROM SQLD;

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       LEAD(SCORE, 2) OVER(PARTITION BY SUBJECT
                               ORDER BY SCORE DESC) AS LEAD
  FROM SQLD;
