SELECT * FROM SQLD;

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       SUM(SCORE) OVER() AS SUM,
       SCORE/SUM(SCORE) OVER() AS "SCORE/SUM",
       RATIO_TO_REPORT(SCORE) OVER() AS RATIO_TO_REPORT
  FROM SQLD;

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       SUM(SCORE) OVER(PARTITION BY SUBJECT) AS SUM,
       SCORE/SUM(SCORE) OVER(PARTITION BY SUBJECT) AS "SCORE/SUM",
       RATIO_TO_REPORT(SCORE) OVER(PARTITION BY SUBJECT) AS RATIO_TO_REPORT
  FROM SQLD;
