SELECT * FROM SQLD;

SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       RANK() OVER(ORDER BY SCORE) AS RANK,
       COUNT(*) OVER() AS COUNT,
       (RANK() OVER(ORDER BY SCORE)-1)/(COUNT(*) OVER()-1) AS "(RANK-1)/(COUNT-1)",
       PERCENT_RANK() OVER(ORDER BY SCORE) AS PERCENT_RANK
  FROM SQLD;
