SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       RANK() OVER(PARTITION BY SUBJECT ORDER BY SCORE) AS RANK,
       COUNT(*) OVER(PARTITION BY SUBJECT) AS COUNT,
       (RANK() OVER(PARTITION BY SUBJECT ORDER BY SCORE)-1)/
       (COUNT(*) OVER(PARTITION BY SUBJECT)-1) AS "(RANK-1)/(COUNT-1)",
       PERCENT_RANK() OVER(PARTITION BY SUBJECT
                               ORDER BY SCORE) AS PERCENT_RANK
  FROM SQLD;
