SELECT STUDENT_NAME,
       SUBJECT,
       SCORE,
       COUNT(*) OVER(PARTITION BY SUBJECT
                         ORDER BY SCORE) AS COUNT,
       COUNT(*) OVER(PARTITION BY SUBJECT) AS TOTAL_COUNT,
       COUNT(*) OVER(PARTITION BY SUBJECT ORDER BY SCORE)/
       COUNT(*) OVER(PARTITION BY SUBJECT) AS "COUNT/TOTAL_COUNT",
       CUME_DIST() OVER(PARTITION BY SUBJECT
                            ORDER BY SCORE) AS CUME_DIST
  FROM SQLD;
