-- SQLD 테이블
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE EXAM_SCORE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE EXAM_SCORE(
    "이름" VARCHAR(16),
    "국어" NUMBER,
    "영어" NUMBER,
    "수학" NUMBER
);

INSERT INTO EXAM_SCORE VALUES ('김기탁', 116, 77, 75);
INSERT INTO EXAM_SCORE VALUES ('김기탁', 101, 69, 80);
INSERT INTO EXAM_SCORE VALUES ('노정인', 118, 62, 60);
INSERT INTO EXAM_SCORE VALUES ('이솔', 96, 72, 70);
INSERT INTO EXAM_SCORE VALUES ('박현준', 103, 77, 55);
INSERT INTO EXAM_SCORE VALUES ('신재석', 78, 66, 61);
INSERT INTO EXAM_SCORE VALUES ('김동엽', 85, 72, 75);
INSERT INTO EXAM_SCORE VALUES ('서인지', 99, 70, 53);
INSERT INTO EXAM_SCORE VALUES ('박혜진', 105, 75, 69);
INSERT INTO EXAM_SCORE VALUES ('안률', 117, 68, 73);

COMMIT;
