SELECT * FROM CATEGORY;

SELECT A.CATEGORY_TYPE,
       A.CATEGORY_NAME,
       B.CATEGORY_TYPE,
       B.CATEGORY_NAME
  FROM CATEGORY A,
       CATEGORY B
 WHERE A.CATEGORY_NAME = B.PARENT_CATEGORY
   AND A.CATEGORY_TYPE = '대';

SELECT A.CATEGORY_TYPE,
       A.CATEGORY_NAME,
       B.CATEGORY_TYPE,
       B.CATEGORY_NAME,
       C.CATEGORY_TYPE,
       C.CATEGORY_NAME
  FROM CATEGORY A,
       CATEGORY B,
       CATEGORY C
 WHERE A.CATEGORY_NAME = B.PARENT_CATEGORY
   AND B.CATEGORY_NAME = C.PARENT_CATEGORY;
