CREATE TABLE TEACHER(
    TEACHER_NO      NUMBER NOT NULL,
    TEACHER_NAME    VARCHAR(20) NOT NULL,
    SUBJECT_ID      VARCHAR(5) NOT NULL,
    MOBILE_NO       VARCHAR(15),
    ADDRESS         VARCHAR(100),
    CONSTRAINT TEACHER_PK PRIMARY KEY(TEACHER_NO),
    CONSTRAINT TEACHER_FK FOREIGN KEY(SUBJECT_ID) REFERENCES SUBJECT(SUBJECT_ID)
);

CREATE TABLE TEACHER_BACKUP AS SELECT * FROM TEACHER;
