ALTER TABLE TEACHER ADD BIRTHDAY VARCHAR(8);

ALTER TABLE TEACHER DROP COLUMN ADDRESS;

ALTER TABLE TEACHER MODIFY(BIRTHDAY VARCHAR(8) DEFAULT '99999999' NOT NULL);

ALTER TABLE TEACHER RENAME COLUMN MOBILE_NO TO HP_NO;

ALTER TABLE TEACHER ADD CONSTRAINT TEACHER_FK FOREIGN KEY(SUBJECT_ID) REFERENCES SUBJECT(SUBJECT_ID);

DROP TABLE SUBJECT;

DROP TABLE SUBJECT CASCADE CONSTRAINT;

TRUNCATE TABLE TEACHER;
