CREATE USER CHOIHYUNMIN IDENTIFIED BY PW1234;

ALTER USER CHOIHYUNMIN IDENTIFIED BY PW5678;

DROP USER CHOIHYUNMIN;

GRANT CREATE SESSION TO CHOIHYUNMIN;
GRANT CREATE USER TO CHOIHYUNMIN;
GRANT CREATE TABLE TO CHOIHYUNMIN;

REVOKE CREATE TABLE FROM CHOIHYUNMIN;

CREATE ROLE CREATE_R;

GRANT CREATE SESSION, CREATE USER, CREATE TABLE TO CREATE_R;

GRANT CREATE_R TO CHOIHYUNMIN;
