SELECT 'S' || 'Q' || 'L' || '개' || '발' || '자' AS SQLD FROM DUAL;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE(
    COL1 VARCHAR(32),
    COL2 VARCHAR(32)
);
INSERT INTO SAMPLE VALUES ('나는', '합격한다');

SELECT * FROM SAMPLE;

SELECT COL1 || ' ' || 'SQLD' || ' ' || COL2 AS RESULT
FROM SAMPLE;
