SELECT SYSDATE FROM DUAL;

SELECT EXTRACT(YEAR FROM SYSDATE) AS YEAR,
       EXTRACT(MONTH FROM SYSDATE) AS MONTH,
       EXTRACT(DAY FROM SYSDATE) AS DAY
FROM DUAL;

SELECT ADD_MONTHS(TO_DATE('2021-12-31', 'YYYY-MM-DD'), -1) AS PREV_MONTH,
       ADD_MONTHS(TO_DATE('2021-12-31', 'YYYY-MM-DD'), 1) AS NEXT_MONTH
FROM DUAL;
