SELECT TO_NUMBER('1234') FROM DUAL;

-- ORA-01722: 수치가 부적합합니다
-- SELECT TO_NUMBER('abc') FROM DUAL;

SELECT TO_CHAR(1234) FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYYMMDD HH24MISS') FROM DUAL;

SELECT TO_DATE('20210602', 'YYYYMMDD') FROM DUAL;
