BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SUBWAY_INFO';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SUBWAY_INFO (
    SUBWAY_LINE INT,
    START_POINT VARCHAR(16),
    END_POINT VARCHAR(16)
);
INSERT INTO SUBWAY_INFO VALUES (1, '인천', '소요산');
INSERT INTO SUBWAY_INFO VALUES (2, '순환선', '순환선');
INSERT INTO SUBWAY_INFO VALUES (3, '대화', '오금');
INSERT INTO SUBWAY_INFO VALUES (4, '오이도', '당고개');
INSERT INTO SUBWAY_INFO VALUES (5, '방화', '마천,상일동');

SELECT SUBWAY_LINE,
       CASE WHEN SUBWAY_LINE = '1' THEN 'BLUE'
            WHEN SUBWAY_LINE = '2' THEN 'GREEN'
            WHEN SUBWAY_LINE = '3' THEN 'ORANGE'
            ELSE 'GRAY'
       END AS LINE_COLOR
FROM SUBWAY_INFO;

SELECT SUBWAY_LINE,
       CASE SUBWAY_LINE
           WHEN 1 THEN 'BLUE'
           WHEN 2 THEN 'GREEN'
           WHEN 3 THEN 'ORANGE'
           ELSE 'GRAY'
       END AS LINE_COLOR
FROM SUBWAY_INFO;

SELECT SUBWAY_LINE,
       DECODE(SUBWAY_LINE, '1', 'BLUE', '2', 'GREEN', '3', 'ORANGE', 'GRAY') AS LINE_COLOR
FROM SUBWAY_INFO;
