BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE (
	COL1	NUMBER,
	COL2	NUMBER,
	COL3	NUMBER
);

INSERT INTO SAMPLE VALUES(NULL, 20, 1);
INSERT INTO SAMPLE VALUES(20, 20, 2);

COMMIT;


SELECT NVL(COL1, COL2) FROM SAMPLE WHERE COL3 = 1;
SELECT NULLIF(COL1, COL2) FROM SAMPLE WHERE COL3 = 2;
SELECT COALESCE(COL1, COL2, COL3) FROM SAMPLE WHERE COL3 = 1;
SELECT ISNULL(COL1, COL2) FROM SAMPLE WHERE COL3 = 1;
