BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE (
	COL1	NUMBER,
	COL2	VARCHAR(1)
);

INSERT INTO SAMPLE VALUES (100, NULL);
INSERT INTO SAMPLE VALUES (200, 'A');
INSERT INTO SAMPLE VALUES (NULL, 'B');
INSERT INTO SAMPLE VALUES (400, 'A');

COMMIT;

SELECT COUNT(COL1) FROM SAMPLE WHERE COL2 IS NOT NULL;
SELECT COL1 FROM SAMPLE WHERE COL2 = NULL;
SELECT COUNT(NVL(COL1,1)) FROM SAMPLE WHERE COL2 = 'B';
SELECT COUNT(NVL(COL2,'NULL')) FROM SAMPLE WHERE COL1 = 100;
