BEGIN
EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEES';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER,
	FIRST_NAME  VARCHAR(64),
	EMAIL	    VARCHAR(64),
	HIRE_DATE   DATE
);

INSERT INTO EMPLOYEES VALUES(198, 'Donald', 'DOCONNEL', '2017-06-21');

COMMIT;


SELECT EMPLOYEE_ID,
       FIRST_NAME AS NAME,
       EMAIL AS "email",
       hire_date
  FROM EMPLOYEES;
