BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE (
	COL1	NUMBER,
	COL2	NUMBER,
	COL3	NUMBER
);

INSERT INTO SAMPLE VALUES(10, NULL, 5);
INSERT INTO SAMPLE VALUES(NULL, 15, 10);
INSERT INTO SAMPLE VALUES(NULL, NULL, 5);
INSERT INTO SAMPLE VALUES(20, 10, NULL);

COMMIT;

SELECT SUM(COALESCE(COL1,COL2,COL3)) FROM SAMPLE;
