BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE1';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE2';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE3';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE1 (
	COL1	NUMBER
);

CREATE TABLE SAMPLE2 (
	COL1	NUMBER
);

CREATE TABLE SAMPLE3 (
	COL1	NUMBER
);

INSERT INTO SAMPLE1 VALUES(1);
INSERT INTO SAMPLE1 VALUES(2);
INSERT INTO SAMPLE1 VALUES(3);
INSERT INTO SAMPLE1 VALUES(4);

INSERT INTO SAMPLE2 VALUES(1);
INSERT INTO SAMPLE2 VALUES(3);
INSERT INTO SAMPLE2 VALUES(5);
INSERT INTO SAMPLE2 VALUES(7);

INSERT INTO SAMPLE3 VALUES(2);
INSERT INTO SAMPLE3 VALUES(4);
INSERT INTO SAMPLE3 VALUES(8);

COMMIT;


SELECT A.COL1, B.COL1, C.COL1
  FROM SAMPLE1 A, SAMPLE2 B, SAMPLE3 C
 WHERE A.COL1 = B.COL1 (+)
   AND A.COL1 = C.COL1 (+);
