BEGIN
EXECUTE IMMEDIATE 'DROP TABLE EMP';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE EMP (
	EMP_ID		VARCHAR(3),
	EMP_STATE	VARCHAR(1)
);

INSERT INTO EMP VALUES('A01','1');
INSERT INTO EMP VALUES('A02','2');
INSERT INTO EMP VALUES('A03','3');
INSERT INTO EMP VALUES('A04','4');

COMMIT;

SELECT EMP_ID,
	   CASE WHEN EMP_STATE = '1' THEN '재직'
	        WHEN EMP_STATE = '2' THEN '휴직'
	        WHEN EMP_STATE = '3' THEN '퇴직'
	    END EMP_STATE
  FROM EMP;

 SELECT EMP_ID,
	    CASE EMP_STATE
	    	WHEN '1' THEN '재직'
	        WHEN '2' THEN '휴직'
	        WHEN '3' THEN '퇴직'
	    ELSE NULL
	     END EMP_STATE
  FROM EMP;

 SELECT EMP_ID,
	    DECODE(EMP_STATE,'1','재직','2','휴직','3','퇴직',' ') AS EMP_STATE
   FROM EMP;

 SELECT EMP_ID,
	    DECODE(EMP_STATE,'1','재직','2','휴직','3','퇴직') AS EMP_STATE
   FROM EMP;
