BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE (
	COL1	NUMBER,
	COL2	NUMBER,
	COL3	VARCHAR(1)
);

INSERT INTO SAMPLE VALUES(10, 0, 'A');
INSERT INTO SAMPLE VALUES(20, 2, 'B');
INSERT INTO SAMPLE VALUES(30, 1, 'A');
INSERT INTO SAMPLE VALUES(40, 4, NULL);

COMMIT;

SELECT COL1/COL2 AS RESULT FROM SAMPLE WHERE COL3 = 'A';
