BEGIN
EXECUTE IMMEDIATE 'DROP TABLE EMP';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE DEPT';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE EMP(
	EMP_ID	VARCHAR(3),
	EMP_NM	VARCHAR(10),
	DEPT_NO	VARCHAR(3)
);

CREATE TABLE DEPT(
	DEPT_NO	VARCHAR(3),
	DETP_NM	VARCHAR(10)
);

INSERT INTO EMP VALUES ('E01','김일','D01');
INSERT INTO EMP VALUES ('E02','김이','D02');
INSERT INTO EMP VALUES ('E03','김삼','D03');

INSERT INTO DEPT VALUES ('D01','개발팀');
INSERT INTO DEPT VALUES ('D02','기획팀');
INSERT INTO DEPT VALUES ('D03','홍보팀');

COMMIT;

SELECT D.DEPT_NO,
	   E.EMP_ID
  FROM EMP E INNER JOIN DEPT D
    ON E.DEPT_NO = D.DEPT_NO;

SELECT D.DEPT_NO,
       E.EMP_ID
  FROM EMP E NATURAL JOIN DEPT D;

SELECT DEPT.DEPT_NO,
       EMP.EMP_ID
  FROM EMP LEFT OUTER JOIN DEPT
    ON EMP.DEPT_NO = DEPT.DEPT_NO;

SELECT D.DEPT_NO,
       E.EMP_ID
  FROM EMP E CROSS JOIN DEPT D;