BEGIN
EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEES';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE JOB_HISTORY';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE EMPLOYEES (
	EMPLOYEE_ID		VARCHAR(3),
	JOB_ID			VARCHAR(10)
);

CREATE TABLE JOB_HISTORY (
	EMPLOYEE_ID		VARCHAR(3),
	JOB_ID			VARCHAR(10)
);

INSERT INTO EMPLOYEES VALUES('101','AC_MGR');
INSERT INTO EMPLOYEES VALUES('102','AD_VP');
INSERT INTO EMPLOYEES VALUES('103','IT_PROG');
INSERT INTO EMPLOYEES VALUES('104','IT_PROG');

INSERT INTO JOB_HISTORY VALUES('101','AC_ACCOUNT');
INSERT INTO JOB_HISTORY VALUES('101','AC_MGR');
INSERT INTO JOB_HISTORY VALUES('102','IT_PROG');

COMMIT;


SELECT EMPLOYEE_ID AS EMP_ID, JOB_ID
  FROM EMPLOYEES
UNION
SELECT EMPLOYEE_ID, JOB_ID AS JOB
  FROM JOB_HISTORY;
