BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE1';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE2';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE1 (
	COL1	NUMBER,
	COL2 	VARCHAR2(1),
	COL3	VARCHAR2(1)
);

CREATE TABLE SAMPLE2 (
	COL1	NUMBER,
	COL2	NUMBER,
	COL3	VARCHAR2(1)
);

INSERT INTO SAMPLE1 VALUES(3,'A','B');
INSERT INTO SAMPLE1 VALUES(2,'B','D');
INSERT INTO SAMPLE1 VALUES(5,'C','S');

INSERT INTO SAMPLE2 VALUES(1,5,'E');
INSERT INTO SAMPLE2 VALUES(4,0,'B');
INSERT INTO SAMPLE2 VALUES(2,9,'S');

COMMIT;


SELECT COL1, COL2 FROM SAMPLE1
UNION ALL
SELECT COL1, COL2, COL3 FROM SAMPLE2;

SELECT COL1, COL2 FROM SAMPLE1
UNION ALL
SELECT COL1, COL3 FROM SAMPLE2 ORDER BY COL1;

SELECT COL1, COL2 FROM SAMPLE1
UNION ALL
SELECT COL1, COL2 FROM SAMPLE2;

SELECT COL1, COL2 FROM SAMPLE1 ORDER BY COL1
UNION ALL
SELECT COL1, COL3 FROM SAMPLE2;
