BEGIN
EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEES';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE EMPLOYEES (
	DEPARTMENT_ID	VARCHAR(2),
	NAME			VARCHAR(15),
	SALARY			NUMBER
);

INSERT INTO EMPLOYEES VALUES('10','Jennifer',4400);
INSERT INTO EMPLOYEES VALUES('10','Pat',6000);
INSERT INTO EMPLOYEES VALUES('10','Alexander',3100);
INSERT INTO EMPLOYEES VALUES('10','Guy',2600);
INSERT INTO EMPLOYEES VALUES('20','Michael',13000);
INSERT INTO EMPLOYEES VALUES('20','Tayler',9600);
INSERT INTO EMPLOYEES VALUES('20','Kimberely',3100);
INSERT INTO EMPLOYEES VALUES('30','Den',11000);
INSERT INTO EMPLOYEES VALUES('30','Sigal',2800);
INSERT INTO EMPLOYEES VALUES('30','Shelli',2900);

COMMIT;


SELECT COUNT(*) FROM (
		SELECT NAME,
			   SALARY
		  FROM EMPLOYEES
		 ORDER BY SALARY DESC
) WHERE ROWNUM <= 5;
