BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TORDER';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE TORDER (
	ORDER_DATE	DATE,
	ORDER_CNT	NUMBER
);

INSERT INTO TORDER VALUES('20210801',10);
INSERT INTO TORDER VALUES('20210802',12);
INSERT INTO TORDER VALUES('20210803',6);
INSERT INTO TORDER VALUES('20210804',8);
INSERT INTO TORDER VALUES('20210805',10);

COMMIT;


SELECT ORDER_DATE,
	   ORDER_CNT,
	   SUM(ORDER_CNT) OVER(ORDER BY ORDER_DATE ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS SUM
  FROM TORDER;
