BEGIN
EXECUTE IMMEDIATE 'DROP TABLE VISIT_HIST';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE VISIT_HIST(
	VISIT_DATE		DATE,
	VISITOR			VARCHAR(10),
	VISIT_CNT		NUMBER
);

INSERT INTO VISIT_HIST VALUES('20210801','에디',1);
INSERT INTO VISIT_HIST VALUES('20210801','루피',2);
INSERT INTO VISIT_HIST VALUES('20210802','크롱',3);
INSERT INTO VISIT_HIST VALUES('20210802','에디',2);
INSERT INTO VISIT_HIST VALUES('20210803','루피',1);
INSERT INTO VISIT_HIST VALUES('20210803','크롱',3);

COMMIT;


SELECT VISIT_DATE,
	   VISITOR,
	   SUM(VISIT_CNT) AS SUM
  FROM VISIT_HIST
 GROUP BY ROLLUP(VISIT_DATE, VISITOR);

SELECT VISIT_DATE,
	   VISITOR,
	   SUM(VISIT_CNT) AS SUM
  FROM VISIT_HIST
 GROUP BY CUBE(VISIT_DATE, VISITOR);

SELECT VISIT_DATE,
	   VISITOR,
	   SUM(VISIT_CNT) AS SUM
  FROM VISIT_HIST
 GROUP BY GROUPING SETS(VISIT_DATE, VISITOR);

SELECT VISIT_DATE,
	   VISITOR,
	   SUM(VISIT_CNT) AS SUM
  FROM VISIT_HIST
 GROUP BY VISIT_DATE, VISITOR;
