BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE1';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE2';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE1(
	COL1	VARCHAR(1),
	COL2	NUMBER
);

CREATE TABLE SAMPLE2(
	COL1	VARCHAR(1),
	COL2	NUMBER
);

INSERT INTO SAMPLE1 VALUES('A',1);
INSERT INTO SAMPLE1 VALUES('B',2);
INSERT INTO SAMPLE1 VALUES('C',3);

INSERT INTO SAMPLE2 VALUES('A',4);
INSERT INTO SAMPLE2 VALUES('C',5);

COMMIT;


SELECT *
  FROM SAMPLE1 A
 WHERE EXISTS (SELECT 'X' FROM SAMPLE2 B
 				WHERE B.COL1 = A.COL1);

SELECT *
  FROM SAMPLE1
 WHERE COL1 IN (SELECT COL1 FROM SAMPLE2);

SELECT *
  FROM SAMPLE1
 WHERE COL1 = (SELECT COL1 FROM SAMPLE2);

SELECT *
  FROM SAMPLE1
 WHERE COL1 = (SELECT COL1 FROM SAMPLE2 WHERE ROWNUM = 1);
