BEGIN
EXECUTE IMMEDIATE 'DROP TABLE FAMILY';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE FAMILY (
	FAMILY_ID	NUMBER,
	FAMILY_NAME	VARCHAR(15),
	PARENT_ID	NUMBER
);

INSERT INTO FAMILY VALUES (1,'할머니',NULL);
INSERT INTO FAMILY VALUES (2,'아빠',3);
INSERT INTO FAMILY VALUES (3,'할아버지',NULL);
INSERT INTO FAMILY VALUES (4,'엄마',1);
INSERT INTO FAMILY VALUES (5,'딸',4);
INSERT INTO FAMILY VALUES (6,'아들',2);

COMMIT;


SELECT * FROM FAMILY
 START WITH PARENT_ID = 4
CONNECT BY FAMILY_ID = PRIOR PARENT_ID;
