BEGIN
EXECUTE IMMEDIATE 'DROP TABLE ORG_INFO';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE ORG_INFO (
	DEPT_CODE	VARCHAR(3),
	DEPT_NAME	VARCHAR(20),
	PARENT_DEPT	VARCHAR(3)
);

INSERT INTO ORG_INFO VALUES('100','이과계열',NULL);
INSERT INTO ORG_INFO VALUES('110','공학','100');
INSERT INTO ORG_INFO VALUES('111','컴퓨터','110');
INSERT INTO ORG_INFO VALUES('112','전자전기','110');
INSERT INTO ORG_INFO VALUES('113','건축','110');
INSERT INTO ORG_INFO VALUES('114','기계','110');
INSERT INTO ORG_INFO VALUES('120','자연','100');
INSERT INTO ORG_INFO VALUES('121','생물','120');
INSERT INTO ORG_INFO VALUES('122','화학','120');
INSERT INTO ORG_INFO VALUES('123','물리','120');
INSERT INTO ORG_INFO VALUES('124','수학','120');
INSERT INTO ORG_INFO VALUES('130','의약','100');
INSERT INTO ORG_INFO VALUES('131','의예','130');
INSERT INTO ORG_INFO VALUES('132','한의예','130');
INSERT INTO ORG_INFO VALUES('133','치의예','130');
INSERT INTO ORG_INFO VALUES('134','약학','130');

COMMIT;


SELECT LEVEL, SYS_CONNECT_BY_PATH(DEPT_NAME, '>') AS ORG
  FROM ORG_INFO
 START WITH PARENT_DEPT IS NULL
CONNECT BY PRIOR DEPT_CODE = PARENT_DEPT;
