BEGIN
EXECUTE IMMEDIATE 'DROP TABLE EXAM_SCORE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE EXAM_SCORE (
	NAME	VARCHAR(10),
	SCORE	NUMBER
);

INSERT INTO EXAM_SCORE VALUES('최웅',94);
INSERT INTO EXAM_SCORE VALUES('국연수',100);
INSERT INTO EXAM_SCORE VALUES('김지웅',97);
INSERT INTO EXAM_SCORE VALUES('엔제이',77);
INSERT INTO EXAM_SCORE VALUES('이솔이',87);
INSERT INTO EXAM_SCORE VALUES('박동일',91);
INSERT INTO EXAM_SCORE VALUES('구은호',66);
INSERT INTO EXAM_SCORE VALUES('정채란',85);
INSERT INTO EXAM_SCORE VALUES('방이훈',80);
INSERT INTO EXAM_SCORE VALUES('임태훈',95);

COMMIT;


SELECT NAME, SCORE
  FROM EXAM_SCORE
 WHERE ROWNUM <= 5
 ORDER BY SCORE DESC;

SELECT NAME, SCORE FROM (
	SELECT NAME, SCORE
	  FROM EXAM_SCORE
	 ORDER BY SCORE DESC )
 WHERE ROWNUM <= 5;

SELECT NAME, SCORE FROM (
	SELECT NAME, SCORE,
		   ROW_NUMBER( ) OVER(ORDER BY SCORE DESC) RN
	  FROM EXAM_SCORE )
 WHERE RN <= 5;

SELECT NAME, SCORE,
	   ROW_NUMBER( ) OVER(ORDER BY SCORE DESC) RN
  FROM EXAM_SCORE
 WHERE RN <= 5;
