BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE1';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAMPLE2';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE SAMPLE1 (
	COL1	VARCHAR(1),
	COL2	NUMBER
);

CREATE TABLE SAMPLE2 (
	COL1 	VARCHAR(1),
	COL2	NUMBER
);

INSERT INTO SAMPLE1 VALUES ('A',1);
INSERT INTO SAMPLE1 VALUES ('B',2);
INSERT INTO SAMPLE1 VALUES ('C',3);

INSERT INTO SAMPLE2 VALUES ('A',1);
INSERT INTO SAMPLE2 VALUES ('A',2);
INSERT INTO SAMPLE2 VALUES ('B',1);
INSERT INTO SAMPLE2 VALUES ('B',2);
INSERT INTO SAMPLE2 VALUES ('C',3);

COMMIT;


SELECT * FROM SAMPLE1
INTERSECT
SELECT * FROM SAMPLE2
UNION ALL
SELECT * FROM SAMPLE2
MINUS
SELECT * FROM SAMPLE1;
