BEGIN
EXECUTE IMMEDIATE 'DROP TABLE EMP';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE EMP (
	DEPT_ID	VARCHAR(2),
	NAME			VARCHAR(15),
	JOB_ID			VARCHAR(10)
);

INSERT INTO EMP VALUES('10','Jennifer','AD_ASST');
INSERT INTO EMP VALUES('10','Pat','IT_PROG');
INSERT INTO EMP VALUES('10','Alexander','MK_REP');
INSERT INTO EMP VALUES('10','Guy','PU_CLERK');
INSERT INTO EMP VALUES('20','Michael','MK_MAN');
INSERT INTO EMP VALUES('20','Kevin','SA_REP');
INSERT INTO EMP VALUES('20','Tayler','SA_REP');
INSERT INTO EMP VALUES('20','Kimberely','ST_MAN');

COMMIT;


SELECT DEPT_ID,
	   JOB_ID,
	   COUNT(*) AS CNT
  FROM EMP
 GROUP BY CUBE(DEPT_ID, JOB_ID)
 ORDER BY DEPT_ID, JOB_ID;
